name: chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  provider: ^6.1.5
  firebase_core: ^4.2.1
  socket_io_client: ^2.0.0
  shared_preferences: ^2.0.15
  dio: ^5.4.3+1
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  jwt_decoder: ^2.0.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/images/avatar/
     - assets/icons/flags/
     - assets/icons/Outline/Messages_Conversation/
     - assets/icons/Outline/Users/
     - assets/icons/Outline/Essentional_UI/
     - assets/icons/Outline/Arrows/
     - assets/icons/Outline/Arrows_Action/
     - assets/icons/Outline/Call/
     - assets/icons/Outline/Faces_Emotions_Stickers/
     - assets/icons/Outline/Notes/
     - assets/icons/Outline/Search/
     - assets/icons/Outline/Security/
     - assets/icons/Outline/Settings_Fine_Tuning/
     - assets/icons/Outline/Time/
     - assets/icons/Outline/Video_Audio_Sound/
     - assets/icons/Bold/Arrows/
     - assets/icons/Bold/Call/
     - assets/icons/Bold/Electronic_Devices/
     - assets/icons/Bold/Essentional_UI/
     - assets/icons/Bold/Files/
     - assets/icons/Bold/Like/
     - assets/icons/Bold/Messages_Conversation/
     - assets/icons/Bold/Money/
     - assets/icons/Bold/Notes/
     - assets/icons/Bold/Time/
     - assets/icons/Bold/Users/
     - assets/icons/Bold/Video_Audio_Sound/
     - assets/icons/Bold_Duotone/Users/
