// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkLxX0cO_6ub0f4dDU3BSyp6PVz4x86l4',
    appId: '1:492593901953:web:fbf4ed859ffaf9b96c7880',
    messagingSenderId: '492593901953',
    projectId: 'chat-2bd94',
    authDomain: 'chat-2bd94.firebaseapp.com',
    storageBucket: 'chat-2bd94.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASRosa8R7x9pu3JDTh6bcwChVZnYtsiq4',
    appId: '1:492593901953:android:ffabe0d3054b40d26c7880',
    messagingSenderId: '492593901953',
    projectId: 'chat-2bd94',
    storageBucket: 'chat-2bd94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrUPf15rMJBvosGSNYANuSaWtc-FG-0Vs',
    appId: '1:492593901953:ios:48ff2623aabbdbc46c7880',
    messagingSenderId: '492593901953',
    projectId: 'chat-2bd94',
    storageBucket: 'chat-2bd94.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
